# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oLLNqcQeGRA4rbw1zezf2qB1Y3m8-ap4
"""

import streamlit as st
import joblib as jb
import pandas as pd

model = jb.load("titanic_project.pkl")

st.title("🚢 Titanic Survival Prediction")
st.write("Enter the Passenger Data for survival prediction")

pclass = st.selectbox("Select Passenger Class", [1, 2, 3])
sex = st.selectbox("Select Gender", ["male", "female"])
sibsp = st.number_input("Enter Number of siblings/spouses", min_value=0, max_value=10, value=0)
parch = st.number_input("Enter Number of parents/children", min_value=0, max_value=10, value=0)
fare = st.number_input("Enter Fare", min_value=0.0, max_value=10000.0, value=0.0)
embarked = st.selectbox("Embarked", ["S", "C", "Q"])
age = st.number_input("Enter Age", min_value=0.0, max_value=100.0, value=0)

if st.button("Predict Survival 🔍"):
    input_dict = {
        "Pclass": [pclass],
        "Sex": [sex],
        "Age": [age],
        "SibSp": [sibsp],
        "Parch": [parch],
        "Fare": [fare],
        "Embarked": [embarked]
    }

    input_df = pd.DataFrame(input_dict)

    input_df['Sex'] = input_df['Sex'].replace({'male': 0, 'female': 1})
    input_df['Embarked'] = input_df['Embarked'].replace({'S': 0, 'C': 1, 'Q': 2})

    model_cols = model.feature_names_in_
    for col in model_cols:
        if col not in input_df.columns:
            input_df[col] = 0

    input_df = input_df[model_cols]

    prediction = model.predict(input_df)

    if prediction[0] == 1:
        st.success("Passenger Survived ✅")
    else:
        st.error("Passenger Not Survived ❌")